name: deploy on push
on: [push]
jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: check out the code to build server
        uses: actions/checkout@v4
      - name: copy file to server
        uses: appleboy/scp-action@v1.0.0
        with:
        host: ${{secrets.HOST}}
        username: ${{secrets.SSH_USER_NAME}}
        port: ${{secrets.SSH_PORT}}
        key: ${{secrets.SSH_KEY}}
        source: "./html/*"
        target: "/var/www/html"
        strip_components: 1
        timeout: "120s" # 适当延长超时时间，这里设置为120秒，可根据实际情况调整